### ISSUE TITLE
After choosing the anime title it stays forever in loading

### ISSUE THREAD

**Issue by JFCSapo** [TaPO4eg3D/HS_Downloader#4]
As the title says
once you pick your anime from the list it stays loading and does not show the anime items.
Not sure if related with python3

**Comment by TaPO4eg3D** [comment]
Thanks for reporting! I will take a look, maybe HS changed their HTML structure.

**Comment by TaPO4eg3D** [comment]
I checked and it seems like everything is working as expected. How do you run the software?

**Comment by JFCSapo** [comment]
first i used the command python3 to launch the main.py
then i used just python
keeps getting stuck
i'll try and download fresh
